name: 🐛 Bug report
description: Report errors or unexpected behavior
labels:
  - bug 🐛
  - unverified ⌛
body:
  - type: markdown
    attributes:
      value: Please make sure to [search for existing issues](https://github.com/LookupEngine/LookupEngine/issues?q=) before filing a new one!
  - type: input
    attributes:
      label: LookupEngine version
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: Having detailed steps helps us reproduce the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: false