name: 💡 Feature or enhancement request
description: Propose something new
labels:
  - feature request 📬
  - improvements ✨
  - unverified ⌛
body:
  - type: textarea
    attributes:
      label: Description of the new feature / enhancement
      placeholder: What is the expected behavior of the proposed feature?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Scenario when this would be used?
      placeholder: What is the scenario this would be used? Why is this important to your workflow as a power user?
    validations:
      required: true
  - type: markdown
    attributes:
      value: Please limit one request per issue.
